name: Develop CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: [self-hosted, macos]

    steps:
    - name: Build Machine
      run: hostname
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        fastlane test
      env:
        GITHUB_TOKEN: ${{ secrets.iOSDependenciesToken }}
