name: Develop CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: [self-hosted, macos]

    steps:
    - name: Build Machine
      run: hostname
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        ./build_and_test.sh
      env:
        GITHUB_TOKEN: ${{ secrets.iOSDependenciesToken }}
    - uses: qapital/junit-to-check-annotations@master
      if: failure()
      with:
        test_result_path: TestSummaries.xml
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
